# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Publish to maven local via Gradle
      run: ./gradlew publishToMavenLocal
    - uses: actions/upload-artifact@v2
      with:
        name: maven-achifact
        path: ~/.m2/repository/com/anatawa12/compile-time-constant


  test-with-example:
    runs-on: ubuntu-latest
    needs: 
      - build
    env:
      RELEASER_CHANGER: gradle-properties
    strategy:
      fail-fast: false
      matrix:
        gradle:
          - "5.1"
          - "7.0"

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/download-artifact@v2
        with:
          name: maven-achifact
          path: ~/.m2/repository/com/anatawa12/compile-time-constant
      # to use get-version
      - uses: anatawa12/something-releaser@v2

      # to use exactly specified version of gradle & wrapper
      - name: Setup Gradle Wrapper
        working-directory: example
        run: |
          touch empty
          ./gradlew --build-file=empty wrapper --gradle-version=${{ matrix.gradle }}
          ./gradlew --build-file=empty wrapper
          rm empty

      - name: run build
        working-directory: example
        run: |
          ./gradlew \
            -I ../example-use-local.init.gradle \
            -P compile-time-constant-version=$(cd .. && get-version) \
            --stacktrace \
              build

  conclude:
    runs-on: ubuntu-latest
    needs:
      - test-with-example
    steps:
      - run: echo "conclude empty action"
